<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="ru" sourcelanguage="en_US">
<context>
    <name>CADBaseLibrary</name>
    <message>
        <location filename="../CdbsModules/CdbsEvn.py" line="30"/>
        <source>Location of your existing CADBase library</source>
        <translation>Локальное расположение данных библиотеки CADBase</translation>
    </message>
</context>
<context>
    <name>CadbaseMacro</name>
    <message>
        <location filename="../CadbaseMacro.py" line="101"/>
        <source>Failed to set path for local library:</source>
        <translation>Не удалось установить путь к локальной библиотеке:</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="106"/>
        <source>Failed with settings base parameters:</source>
        <translation>Не удалось установить основные параметры: </translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="132"/>
        <source>CADBase Library</source>
        <translation>Библиотека CADBase</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="193"/>
        <source>Token not found</source>
        <translation>Токен не найден</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="215"/>
        <source>Processing the part...</source>
        <translation>Обработка детали...</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="239"/>
        <source>Processing for preview the part...</source>
        <translation>Обработка для предпросмотра детали...</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="260"/>
        <source>CADBase Library Configuration</source>
        <translation>Конфигурация библиотеки CADBase</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="278"/>
        <source>Local location of your existing CADBase library</source>
        <translation>Локальное расположение данных библиотеки CADBase</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="285"/>
        <source>Changes not accepted</source>
        <translation>Изменения отменены</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="294"/>
        <source>Please restart Blender</source>
        <translation>Пожалуйста, перезапустите Blender</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="299"/>
        <source>Configuration updated</source>
        <translation>Конфигурация обновлена</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="314"/>
        <source>Library path not found:</source>
        <translation>Путь к библиотеке не найден:</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="322"/>
        <source>Received data about components is not suitable for processing</source>
        <translation>Полученные данные о компонентах не пригодны для обработки.</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="325"/>
        <source>You don&apos;t have favorite components</source>
        <translation>У вас нет избранных компонентов</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="328"/>
        <source>Component UUID:</source>
        <translation>Идентификатор компонента (UUID):</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="332"/>
        <source>Component list update finished</source>
        <translation>Завершенно обновление списка компонентов</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="338"/>
        <source>Not set UUID for select component</source>
        <translation>Не установлен UUID для выбранного компонента</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="343"/>
        <source>Received data about component is not suitable for processing</source>
        <translation>Полученные данные о компоненте не подходят для обработки</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="346"/>
        <source>No modifications for the component</source>
        <translation>У компонента нет модификаций</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="350"/>
        <source>Updated the list of component modifications</source>
        <translation>Обновить список компонентов модификации</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="356"/>
        <source>Not set UUID for select modification</source>
        <translation>Не установлен UUID для выбранной модификации</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="361"/>
        <source>Received data about fileset is not suitable for processing</source>
        <translation>Полученные данные о наборе файлов не подходят для обработки</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="364"/>
        <source>Fileset not found for Blender</source>
        <translation>Набор файлов для Blender не найден</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="369"/>
        <source>Received data about files of fileset is not suitable for processing</source>
        <translation>Получены данные о файлах набора файлов, не пригодны для обработки</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="372"/>
        <source>No files in fileset</source>
        <translation>В наборе файлов нет файлов</translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="382"/>
        <source>Download file(s):</source>
        <translation>Скачанных файлов: </translation>
    </message>
    <message>
        <location filename="../CadbaseMacro.py" line="383"/>
        <source>Component modification files update completed</source>
        <translation>Файлы модификации компонента обновлены</translation>
    </message>
</context>
<context>
    <name>CdbsApi</name>
    <message>
        <location filename="../CdbsModules/CdbsApi.py" line="15"/>
        <source>Successful processing request</source>
        <translation>Успешная обработка запроса</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsApi.py" line="17"/>
        <source>Failed processing request</source>
        <translation>Обработка запроса не удалась</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsApi.py" line="24"/>
        <source>Getting data...</source>
        <translation>Получение данных...</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsApi.py" line="36"/>
        <source>Query include body:</source>
        <translation>Тело запроса:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsApi.py" line="42"/>
        <source>Exception when trying to sending the request:</source>
        <translation>Исключение при попытке отправить запрос:</translation>
    </message>
</context>
<context>
    <name>CdbsAuth</name>
    <message>
        <location filename="../CdbsModules/CdbsAuth.py" line="14"/>
        <source>Successful authorization</source>
        <translation>Успешная авторизация</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsAuth.py" line="16"/>
        <source>Failed authorization</source>
        <translation>Ошибка при авторизации</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsAuth.py" line="23"/>
        <source>Getting a new token, please wait.</source>
        <translation>Получение нового токена, пожалуйста, подождите.</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsAuth.py" line="42"/>
        <source>Exception when trying to login:</source>
        <translation>Исключение при попытке авторизироваться</translation>
    </message>
</context>
<context>
    <name>CdbsStorage</name>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="21"/>
        <source>Preparing for uploading files...</source>
        <translation>Подготовка к загрузке файлов...</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="25"/>
        <source>To upload files, you must select the modification folder</source>
        <translation>Для загрузки файлов необходимо выбрать папку модификации</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="27"/>
        <source>Modification UUID:</source>
        <translation>Идентификатор модификации:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="29"/>
        <source>To upload files, you must select a modification (so that the macro can determine the target set of files)</source>
        <translation>Для загрузки файлов необходимо выбрать модификацию (чтобы макрос мог определить целевой набор файлов)</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="43"/>
        <source>Getting fileset UUID...</source>
        <translation>Получение идентификатора набора файлов</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="48"/>
        <source>Fileset UUID:</source>
        <translation>Идентификатор набора файлов</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="50"/>
        <source>Creating a new set of files for Blender</source>
        <translation>Создание нового набора файлов для Blender</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="55"/>
        <source>Error occurred while getting the UUID of the file set</source>
        <translation>Произошла ошибка при получении UUID набора файлов.</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="63"/>
        <source>Error occurred while confirming the upload of files, the files were not uploaded to correctly</source>
        <translation>Произошла ошибка при подтверждении загрузки файлов, файлы были загружены не правильно</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="67"/>
        <source>No files found for upload</source>
        <translation>Файлы для загрузки не найдены</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="70"/>
        <source>Success upload files to CADBase storage:</source>
        <translation>Файлы успешно загружены в хранилище CADBase:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="38"/>
        <source>Files in the CADBase storage have been updated successfully</source>
        <translation>Файлы в хранилище CADBase успешно обновлены</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="80"/>
        <source>Last clicked dir:</source>
        <translation>Последний выбор:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="85"/>
        <source>Local files:</source>
        <translation>Локальные файлы:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="96"/>
        <source>Cloud filenames:</source>
        <translation>Файлы в облаке (удалённом хранилище):</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="100"/>
        <source>The local file has a cloud version:</source>
        <translation>Локальный файл имеет облачную версию</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="104"/>
        <source>Local file does not have a cloud version:</source>
        <translation>Локальный файл не имеет облачную версию</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="107"/>
        <source>New files to upload:</source>
        <translation>Новые файлы для загрузки:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="115"/>
        <source>Blake3 import error:</source>
        <translation>Ошибка при подключении Blake3:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="116"/>
        <source>Warning: for compare hashes need install `blake3`. Please try to install it with: `pip install blake3` or some other way.</source>
        <translation>Внимание: для сравнения хэшей необходимо установить `blake3`. Пожалуйста, попробуйте установить его с помощью: `pip install blake3` или каким-либо другим способом.</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="122"/>
        <source>File hash from CADBase not found, this file is skipped:</source>
        <translation>Хэш файла из CADBase не получен, этот файл пропущен:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="126"/>
        <source>Warning: found not file and it skipped</source>
        <translation>Предупреждение: файл не найден и пропущен</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="133"/>
        <source>Error calculating hash for local file</source>
        <translation>Ошибка при вычислении хеша для локального файла</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="135"/>
        <source>Hash file</source>
        <translation>Хэш файла</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="135"/>
        <source>local</source>
        <translation>локальный</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="135"/>
        <source>cloud</source>
        <translation>облачное храшилище</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="149"/>
        <source>Selected files to upload:</source>
        <translation>Выбранные файлы для загрузки:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="155"/>
        <source>Uploading files to cloud storage (this can take a long time)</source>
        <translation>Загрузка файлов в облачное хранилище (это может занять много времени)</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="158"/>
        <source>Failed to upload files</source>
        <translation>Не удалось загрузить файлы</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="163"/>
        <source>Confirmation of successful files upload:</source>
        <translation>Подтверждение успешной загрузки файлов:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="172"/>
        <source>Completed upload:</source>
        <translation>Выполнена загрузка:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorage.py" line="182"/>
        <source>Filename:</source>
        <translation>Имя файла:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="91"/>
        <source>time:</source>
        <translation>время:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="97"/>
        <source>sec</source>
        <translation>сек</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="97"/>
        <source>Total time:</source>
        <translation>Общее время:</translation>
    </message>
</context>
<context>
    <name>CdbsStorageApi</name>
    <message>
        <location filename="../CdbsModules/CdbsStorageApi.py" line="12"/>
        <source>Preparing for upload file...</source>
        <translation>Подготовка к отправке файла...</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorageApi.py" line="21"/>
        <source>Can not read file...</source>
        <translation>Не могу прочитать файл...</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorageApi.py" line="28"/>
        <source>Upload file...</source>
        <translation>Загрузка файла...</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorageApi.py" line="32"/>
        <source>Exception in upload file:</source>
        <translation>Исключение при загрузке файла:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/CdbsStorageApi.py" line="35"/>
        <source>File uploaded. Response bytes:</source>
        <translation>Файл загружен. Содержимое ответа:</translation>
    </message>
</context>
<context>
    <name>DataHandler</name>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="45"/>
        <source>Success</source>
        <translation>Успех</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="48"/>
        <source>Failed, status code:</source>
        <translation>Ошибка, код состояния:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="111"/>
        <source>Error occurred:</source>
        <translation>Возникла ошибка:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="62"/>
        <source>File already exists and skipped:</source>
        <translation>Файл уже существует и пропущен:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="74"/>
        <source>Exception in download file:</source>
        <translation>Исключение при скачивании файла:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="81"/>
        <source>Error:</source>
        <translation>Ошибка:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="91"/>
        <source>path:</source>
        <translation>путь:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="102"/>
        <source>Data processing, please wait.</source>
        <translation>Обработка данных, пожалуйста, подождите.</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="104"/>
        <source>Not found file with response</source>
        <translation>Не найден файл с ответом</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="115"/>
        <source>Exception occurred while parsing the server response:</source>
        <translation>Произошло исключение при анализе ответа сервера:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="121"/>
        <source>No data found to delete</source>
        <translation>Не найдено данных для удаления</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="134"/>
        <source>Exception occurred while trying to save old response:</source>
        <translation>Возникло исключение при попытке сохранить старый ответ:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="139"/>
        <source>removed</source>
        <translation>удалён</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="145"/>
        <source>Please delete this file for correct operation:</source>
        <translation>Пожалуйста, удалите этот файл для корректной работы:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="155"/>
        <source>Exception occurred while trying to write the file:</source>
        <translation>Возникло исключение при попытке записи файла:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="163"/>
        <source>Selected</source>
        <translation>Выбрано</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="166"/>
        <source>Exception when trying to read information from the file:</source>
        <translation>Исключение при попытке прочитать информацию из файла:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="175"/>
        <source>Failed to parse GraphQL before deep parsing:</source>
        <translation>Не удалось получить данные ответа (GraphQL) для дальнейшей обработки:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="180"/>
        <source>Received data is not suitable for processing about</source>
        <translation>Полученны не подходящие для обработки данные о</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="194"/>
        <source>Structure data:</source>
        <translation>Структура данных:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="196"/>
        <source>Not found data for UUID selection:</source>
        <translation>Не найдены данные для выбора UUID:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="199"/>
        <source>Structure vars:</source>
        <translation>Структурные переменные:</translation>
    </message>
    <message>
        <location filename="../CdbsModules/DataHandler.py" line="205"/>
        <source>UUID of structure data:</source>
        <translation>UUID из структуры данных:</translation>
    </message>
</context>
<context>
    <name>InitGui</name>
    <message>
        <location filename="../InitGui.py" line="8"/>
        <source>CADBase Library</source>
        <translation>Библиотека CADBase</translation>
    </message>
    <message>
        <location filename="../InitGui.py" line="7"/>
        <source>The workbench is designed to use components (parts) from CADBase in the Blender interface. \
Component modifications contain sets of files for various CAD systems. \
This workbench will work with data from the Blender set, without downloading documentation and data from other file sets.</source>
        <translation>Верстак предназначен для использования компонентов (деталей) из CADBase в интерфейсе Blender.
Модификации компонента содержат наборы файлов для различных САПР. \
Этот верстак будет работать данными из набора для Blender, без скачивания документации и данных из других наборов файлов.</translation>
    </message>
</context>
</TS>
